In [1]:
import numpy as np
import pandas as pd


from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
path = '/content/drive/MyDrive/Colab Notebooks/Mastermind_colab/Personal_notebooks/Proyectos/Regresion_lineal/Ejercicio_2/datos_airbnb - datos_airbnb.csv'

df = pd.read_csv(path)

In [ ]:
df.head()

In [5]:
df.sample(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
35733,28359512,East Village Pad with a View,131454177,Ali,Manhattan,East Village,40.72907,-73.98388,Entire home/apt,195,7,0,NaN,NaN,1,295
40093,31121525,"Charming 2Br in the middle of LES, SoHo",214869202,Joey,Manhattan,Lower East Side,40.72181,-73.98946,Entire home/apt,250,1,36,2019-06-22,6.17,1,10
42494,32984848,2 Bedroom Clean & Simple in Manhattan,241567925,Paraskevi,Manhattan,Chinatown,40.71358,-73.99062,Entire home/apt,199,3,7,2019-06-02,1.88,1,49
39235,30587338,Spacious 2 bedroom near Central Park,44886301,Dayane,Manhattan,Upper East Side,40.76991,-73.95327,Private room,175,3,0,NaN,NaN,2,0
3582,2141470,Centrally located Midtown East 1 BR,10928857,Ashley,Manhattan,Murray Hill,40.74487,-73.97452,Entire home/apt,125,2,8,2015-01-02,0.13,1,0
40330,31280733,Williamsburg Private Room in Homey Space by Tr...,23308549,John,Brooklyn,Williamsburg,40.71388,-73.95744,Private room,75,2,1,2019-02-12,0.20,1,0
29043,22339390,Easin' on the Artist Row,162436632,Kaj,Manhattan,East Village,40.72260,-73.97591,Private room,65,7,9,2019-05-06,0.71,1,144
45372,34708657,Duplex 4 bed apt fantastic place for 10,261779847,Ben,Manhattan,East Harlem,40.79803,-73.94185,Entire home/apt,350,3,8,2019-06-30,5.11,1,231
26677,21204708,Quiet East Village Studio next to snug coffee ...,23386210,John,Manhattan,East Village,40.72690,-73.98470,Entire home/apt,142,10,22,2018-12-30,1.04,1,0
28552,22122614,Spacious Family Space - 2 Bedrooms,161617875,Tyge,Manhattan,Washington Heights,40.85244,-73.94050,Entire home/apt,150,2,30,2019-06-16,1.61,2,109

In [ ]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  object
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  object
 4   neighbourhood_group             48895 non-null  object
 5   neighbourhood                   48895 non-null  object
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  object
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), object(6)
memory usage: 6.0+ MB

In [12]:
df.isnull().any()

id                                False
name                               True
host_id                           False
host_name                          True
neighbourhood_group               False
neighbourhood                     False
latitude                          False
longitude                         False
room_type                         False
price                             False
minimum_nights                    False
number_of_reviews                 False
last_review                        True
reviews_per_month                  True
calculated_host_listings_count    False
availability_365                  False
dtype: bool

# ¿Dirías que este Dataset está limpio? ¿Se puede usar para entrenar un modelo?

Como he podido comprobar haciendo una primera exploración rápida de los datos, el Dataset cuenta con algunos campos que contienen errores de formato (por ejemplo con strings en vez de fechas), existen valores nulos con lo que tenemos que lidiar y hay campos que son irrrelevantes para nuestro modelo, los cuales pdríamos eliminar sin problema para mejorar el rendimiento de nuestro modelo.

# En caso que no, ¿qué técnicas de Data Cleaning necesita?

Hay varias modificaciones quer deberíamos hacer antes de poder utilizar este DF para entrenar un modelo:
- Las feature variables de `id` `name`	`host_id`	`host_name` son irrelevantes para nuestro modelo, por lo que podríamos eliminarlas sin problemas. Al eliminarnos, también nos evitamos tener que lidiar con los NaN que existían en los campos de `name` y `host_name`

- Tendríamos que lidiar con los NaN cuando no se tiene ninguna reseña, ya que en los campos de `last_review` y `review_per_month`, cuando no se tienen reseñas, aparecen valores NaN.

- Las fechas de la útima reseña (`last_review`) no están en formato DateTime, por lo que habría que formatear dicho campo.

#¿Borrarías alguna columna?

Como he comentado anteriormente, las feature variables de `id` `name`	`host_id`	`host_name` son irrelevantes para nuestro modelo, por lo que podríamos eliminarlas sin problemas. También podrían eliminarse los campos de latitud y longitud, ya que tenemos el barrio en el que se encuentran, que es lo que realmente nos ofrece info de cómo afecta la localización al precio.

# ¿Cuál es nuestro target variable?

La target variable cuyo resultado queremos predecir es el **PRECIO**

#¿Qué columnas necesitan Encoding? ¿Y Scaling? ¡Aplica estas técnicas donde sea necesario!

In [15]:
df.drop(["id",	"name", "host_id",	"host_name"], inplace = True, axis=1)

In [17]:
df.drop(["latitude",	"longitude"], inplace = True, axis=1) #Sorry, se me había olvidado eliminar estas jeje

In [19]:
df.head()

,neighbourhood_group,neighbourhood,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,Brooklyn,Kensington,Private room,149,1,9,2018-10-19,0.21,6,365
1,Manhattan,Midtown,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,Manhattan,Harlem,Private room,150,3,0,NaN,NaN,1,365
3,Brooklyn,Clinton Hill,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,Manhattan,East Harlem,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   neighbourhood_group             48895 non-null  object
 1   neighbourhood                   48895 non-null  object
 2   room_type                       48895 non-null  object
 3   price                           48895 non-null  int64
 4   minimum_nights                  48895 non-null  int64
 5   number_of_reviews               48895 non-null  int64
 6   last_review                     38843 non-null  object
 7   reviews_per_month               38843 non-null  float64
 8   calculated_host_listings_count  48895 non-null  int64
 9   availability_365                48895 non-null  int64
dtypes: float64(1), int64(5), object(4)
memory usage: 3.7+ MB

In [21]:
df.isnull().any()

neighbourhood_group               False
neighbourhood                     False
room_type                         False
price                             False
minimum_nights                    False
number_of_reviews                 False
last_review                        True
reviews_per_month                  True
calculated_host_listings_count    False
availability_365                  False
dtype: bool